#!/bin/bash

bin_dir="$( cd "$( dirname "$0" )" && pwd )"

source ${bin_dir}/website_config

source ${bin_dir}/error_functions
source ${bin_dir}/rsync_functions
source ${bin_dir}/confirm_functions

changes_not_in_git=`git status -s ${wordpress_local_source} | wc -l`

if [ "$changes_not_in_git" != "0" ]; then
    git status ${wordpress_local_source}
    echo "*** There were local files not checked in ***"
    exit 1
fi

echo Checking for remote changes
rsync_list_changes $wordpress_local_source $wordpress_remote_target --exclude='wp-content/uploads'

if confirm "Proceed with these changes?"; then
    echo Copying changes to remote site
    rsync_copy_changes $wordpress_local_source $wordpress_remote_target --exclude='wp-content/uploads'
    exit 0
else
    echo Aborted

    exit 1
fi
