#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage: $0 <log_prefix> <log_dir>"
    exit 1
fi

bin_dir="$( cd "$( dirname "$0" )" && pwd )"

source ${bin_dir}/website_config

source ${bin_dir}/error_functions
source ${bin_dir}/rsync_functions

log_prefix=$1
log_dir=$2

command_log_file=$logs_dir/get_${log_prefix}.log

todays_date=`date +%Y%m%d`
date_stamp=`date +%F_%H-%M-%S`
year=`date +%Y`

local_log_dir=$logs_dir/$log_dir/$year
mkdir -p $local_log_dir

rsync_copy_changes $remote_logs_dir/${log_prefix}-*.gz $local_log_dir > $command_log_file

if [[ $? -ne 0 ]]; then
    echo "*** Failed to get log files ***"
    cat {$command_log_file}
fi
