#!/bin/bash

set -e

if [ $# -gt 1 ]; then
    echo "Usage: $0 [-y]"
    exit
fi

bin_dir="$( cd "$( dirname "$0" )" && pwd )"

source ${bin_dir}/website_config

mkdir -p $debug_dir

prompt=1

php ${bin_dir}/fetch_wordpress_db.php $remote_site_url $admin_user $admin_password $debug_dir $remote_backups_dir $local_url $local_wordpress_server $local_wordpress_user $local_wordpress_password $local_wordpress_db $local_backups_dir $prompt

${bin_dir}/delete_remote_backups
