#!/bin/bash

set -e

bin_dir="$( cd "$( dirname "$0" )" && pwd )"

source ${bin_dir}/website_config

source ${bin_dir}/error_functions
source ${bin_dir}/rsync_functions
source ${bin_dir}/confirm_functions
source ${bin_dir}/svn_functions

svn_ensure_changes_checked_in $wordpress_local_uploads

echo Checking for remote changes
rsync_list_changes $wordpress_remote_uploads $wordpress_local_uploads

if confirm "Proceed with these changes?"; then
    echo Copying uploads from remote site
    rsync_copy_changes_no_mods $wordpress_remote_uploads $wordpress_local_uploads
    exit 0
else
    echo Aborted

    exit 1
fi
